spring:
  datasource:
    hikari:
      primary:
        jdbc-url: jdbc:mariadb://localhost:3307/test
        username: root
        driver-class-name: org.mariadb.jdbc.Driver
      secondary:
        jdbc-url: jdbc:mariadb://localhost:3308/test
        username: root
        password : Asdf1234!
        driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
logging:
  level:
    root: info